export const reportOptions = {
    User_Acquisition: 'User Acquisition',
    Acquisition_Traffic: 'Acquisition Traffic',
    Acquisition_Goal_Report: 'Acquisition Goal Report',
    Engagement_Events: 'Engagement Events',
    Engagement_Conversions: 'Engagement Conversions',
    Engagement_Pages_Screens: 'Engagement Pages Screens',
    Engagement_Landing_page: 'Engagement Landing Page',
    Monetisation_Ecommerce_purchases: 'Monetisation Ecommerce Purchases',
    Monetisation_Item_Lists: 'Monetisation Item Lists',
    Monetisation_Overview_Promotion: 'Monetisation Overview Promotion',
    Demographics_details_Interests: 'Demographics Details Interests',
    Demographics_details_Geo_Language: 'Demographics Details Geo Language',
    Tech_details: 'Tech Details',
  };